### ISSUE TITLE
Menu items with missing localization resources cause all menu items to fail to localize

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#825] opened 2024-04-01 19:34 UTC
**Describe the bug**
Tom showed me an extension with a contributed menu JSON file. That menu JSON referenced a localization key that wasn't included in the localized resources. All menu items then failed to localize instead of just the ones with missing keys.

**Expected behavior**
All menu items that include localized keys should render properly instead of them all failing.

**Comment by tjcouch-sil** [comment] 2024-04-01 19:39
I have also found this. It is quite annoying. However, I believe this is possibly by design. We decided that requesting a localized string for a key that doesn't have a value should throw in development, and I believe that's what's happening here. In production, we return the localized string key and log a warning to my understanding. Maybe we should consider revising this design overall or making it very obvious in some other way what's going wrong (maybe we can implement toasts? Or renderer error log?).

**Comment by lyonsil** [comment] 2024-04-01 19:43
I don't remember if we settled on this or if it is by accident.  Either way, it seemed confusing to a couple of our devs, so we might want to rethink it.

**Comment by tjcouch-sil** [comment] 2024-07-01 14:29
At some point recently, we changed the localization service to warn when it doesn't find a string for a key instead of throwing an error, so this is now fixed.

**Closed by tjcouch-sil** 2024-07-01 14:29 UTC
Labels: bug
