### ISSUE TITLE
macOS: no new tabs

### ISSUE THREAD

**Issue by merchako** [paranext/paranext-core#1179] opened 2024-09-27 21:19 UTC
**Describe the bug**
When taking actions that should open a new tab in Platform or Studio, nothing happens.

**To Reproduce**

1. Go to Main Hamburger (top left)
2. Click on any of

    * Open Scripture Editor
    * Open Resource Viewer
    * Download/Install Resources
    * Settings
    * About Platform.Bible
    * Exit

3. Notice that nothing happens

**Expected behavior**
Some new tab should have opened. (Or in the case of Exit, the window or app should have closed.)

https://github.com/user-attachments/assets/b8266d0a-6ef9-44fc-b324-25c6a119dc71

Platform [main.log](https://github.com/user-attachments/files/17170583/main.log)

Paratext Studio [main.log](https://github.com/user-attachments/files/17170581/main.log)

**Comment by tjcouch-sil** [comment] 2024-09-27 21:22
Is this always reproducible on your machine? If you restart your computer, does it still do this? Did it do this in the past with previous builds? Before doing anything more, could you please [attach your log](https://github.com/paranext/paranext/wiki/Troubleshooting-Guide#log-file-location)? Thanks!

**Comment by lyonsil** [comment] 2024-09-27 21:33
Probably a duplicate of #1177, but we will need to fix that and try again to be certain.

**Comment by merchako** [comment] 2024-09-27 21:42
In Paratext Studio, upon initial open, no window appears, and I get an OS dialog with an error

![Screenshot 2024-09-27 at 16 39 47](https://github.com/user-attachments/assets/98f1e9c6-aa28-4940-b8a2-c22e87315900)

If I open it again, the window appears (with OP behavior).

**Comment by tjcouch-sil** [comment] 2024-09-27 21:45
Interesting... If you close the application completely by right clicking in the dock and closing, does opening it after that change anything?

**Comment by merchako** [comment] 2024-09-28 12:59
I played around with different open/close scenarios to figure our when I get the EADDRUNUSE error, and what I noticed makes so much sense: I get the error when either 

* Platform is already open and I open Studio, or 
* Studio is already open and I open Platform.

Who'd a thunk? 🫠

**Comment by tjcouch-sil** [comment] 2024-09-30 13:30
Ah yeah, they use the same port right now. Might be nice to make them use different ports since they use different file directories and such.

Anyway is the original problem always reproducible on your machine? If you restart your computer, does it still do it? Did it do this in the past with previous builds? Could you please [attach your log](https://github.com/paranext/paranext/wiki/Troubleshooting-Guide#log-file-location) when this happens? Thanks!

**Comment by merchako** [comment] 2024-09-30 15:14
I can't quite recall if this is acting worse than the previous build, but I think it is in this respect. You can find logs in the OP.

**Comment by tjcouch-sil** [comment] 2024-09-30 15:23
I believe this error in the log:

> System.IO.FileLoadException: Can't load ICU library (version 74)
File name: 'icuuc'
   at Icu.NativeMethods.LoadIcuLibrary(String libraryName)
   at Icu.NativeMethods.get_IcuCommonLibHandle()
   at Icu.NativeMethods.u_init(ErrorCode& errorCode)
   at Icu.Wrapper.Init()
   at Paratext.Data.Languages.WritingSystemRepository.Initialize(IWritingSystemRepository`1 repository)
   at Paratext.Data.ParatextData.Initialize(String settingsDir, Boolean initializePt7Data)
   at Paranext.DataProvider.ParatextUtils.ParatextGlobals.SetParatextDataPath(String dataFolderPath) in /Users/runner/work/paranext-core/paranext-core/c-sharp/ParatextUtils/ParatextGlobals.cs:line 45
   at Paranext.DataProvider.ParatextUtils.ParatextGlobals.Initialize(String dataFolderPath) in /Users/runner/work/paranext-core/paranext-core/c-sharp/ParatextUtils/ParatextGlobals.cs:line 38
   at Paranext.DataProvider.Projects.LocalParatextProjects.Initialize(Boolean shouldIncludePT9ProjectsOnWindows) in /Users/runner/work/paranext-core/paranext-core/c-sharp/Projects/LocalParatextProjects.cs:line 68
   at Paranext.DataProvider.Projects.ParatextProjectDataProviderFactory.StartFactory() in /Users/runner/work/paranext-core/paranext-core/c-sharp/Projects/ParatextProjectDataProviderFactory.cs:line 37
   at Paranext.DataProvider.Projects.ProjectDataProviderFactory.Initialize() in /Users/runner/work/paranext-core/paranext-core/c-sharp/Projects/ProjectDataProviderFactory.cs:line 27
   at Paranext.DataProvider.Program.Main() in /Users/runner/work/paranext-core/paranext-core/c-sharp/Program.cs:line 37
   at Paranext.DataProvider.Program.Main() in /Users/runner/work/paranext-core/paranext-core/c-sharp/Program.cs:line 60
   at Paranext.DataProvider.Program.<Main>()


Indicates this is a duplicate of #1177. I believe the problems you're seeing with many things are a result of this underlying issue. With this error, the software can't find the Scripture projects/resources on your system, so things just don't open. Or they open with a list of 0 projects available to select. What do you say we close this @merchako ?

**Comment by merchako** [comment] 2024-10-01 14:16
Seems fine to me. I posted this to give y'all more resources not knowing if it was duplicate or not. Do what seems best to you!

**Comment by tjcouch-sil** [comment] 2024-10-01 14:45
Closed as duplicate of #1177

**Closed by tjcouch-sil** 2024-10-01 14:45 UTC
Labels: bug
