### ISSUE TITLE
Sign the macOS app

### ISSUE THREAD

**Issue by Sebastian-ubs** [paranext/paranext-core#1247] opened 2024-10-29 12:02 UTC
**User Story**
As a user on macOS, I want to be able to launch the app without a work around or unsafe confirmation so that I can use Paratext.

**Description**
https://discord.com/channels/1064938364597436416/1102584891545223228/1300645143396749316
> There is a discussion going over in Slack about signing applications for macOS. Chris Hubbard is willing to help set that up. Will the build for the end of the year need to be signed? Do we have an answer on who will own and hold the certificates? I presume the PT9  Windows build is signed and the certs would be held similarly. @Glenn et al.

**Comment by lyonsil** [comment] 2024-10-29 14:03
This is a duplicate of #1172

**Closed by lyonsil** 2024-10-29 14:03 UTC
Labels: enhancement, ux

**Comment by Sebastian-ubs** [comment] 2024-10-29 14:11
Thank you.
- I've added now added that one to https://github.com/paranext/roadmap/issues/48
